
variables:
  BuildConfiguration: Release

jobs:
  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: src/ZeroLog.sln
          arguments: --configuration $(BuildConfiguration)

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: src/**/*.Tests.csproj
          arguments: --configuration $(BuildConfiguration)

      - task: DotNetCoreCLI@2
        displayName: Pack
        inputs:
          command: pack
          packagesToPack: src/**/*.csproj
          configuration: $(BuildConfiguration)
          packDirectory: $(Build.ArtifactStagingDirectory)
          nobuild: true
          verbosityPack: Minimal

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          ArtifactName: NuGet
