<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CS8002</NoWarn>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroLog\ZeroLog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet.TestAdapter" VersionOverride="0.15.8" />
    <PackageReference Include="HdrHistogram" VersionOverride="2.5.0" />
    <PackageReference Include="Fody" PrivateAssets="all" />
    <PackageReference Include="InlineIL.Fody" PrivateAssets="all" />
    <PackageReference Include="log4net" VersionOverride="3.4.0" />
    <PackageReference Include="NLog" VersionOverride="6.2.0" />
    <PackageReference Include="Serilog" VersionOverride="4.4.0" />
    <PackageReference Include="ZLogger" VersionOverride="2.5.10" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ZeroLog.Tests\TestAppender.cs" Link="Tools\TestAppender.cs" />
  </ItemGroup>

</Project>
