//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace ZeroLog;

#nullable enable

partial class LogMessage
{
    /// <summary>
    /// Appends a value of type <c>bool</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(bool value)
    {
        InternalAppendValueType(value, ArgumentType.Boolean);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>bool?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(bool? value)
    {
        InternalAppendValueType(value, ArgumentType.Boolean);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>bool</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, bool value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Boolean);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>bool?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, bool? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Boolean);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>byte</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(byte value)
    {
        InternalAppendValueType(value, ArgumentType.Byte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>byte?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(byte? value)
    {
        InternalAppendValueType(value, ArgumentType.Byte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>byte</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(byte value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Byte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>byte?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(byte? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Byte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>byte</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, byte value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Byte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>byte?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, byte? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Byte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>sbyte</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(sbyte value)
    {
        InternalAppendValueType(value, ArgumentType.SByte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>sbyte?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(sbyte? value)
    {
        InternalAppendValueType(value, ArgumentType.SByte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>sbyte</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(sbyte value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.SByte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>sbyte?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(sbyte? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.SByte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>sbyte</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, sbyte value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.SByte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>sbyte?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, sbyte? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.SByte);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>char</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(char value)
    {
        InternalAppendValueType(value, ArgumentType.Char);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>char?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(char? value)
    {
        InternalAppendValueType(value, ArgumentType.Char);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>char</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, char value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Char);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>char?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, char? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Char);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>short</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(short value)
    {
        InternalAppendValueType(value, ArgumentType.Int16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>short?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(short? value)
    {
        InternalAppendValueType(value, ArgumentType.Int16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>short</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(short value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Int16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>short?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(short? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Int16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>short</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, short value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Int16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>short?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, short? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Int16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ushort</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(ushort value)
    {
        InternalAppendValueType(value, ArgumentType.UInt16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ushort?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(ushort? value)
    {
        InternalAppendValueType(value, ArgumentType.UInt16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ushort</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(ushort value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UInt16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ushort?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(ushort? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UInt16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ushort</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, ushort value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UInt16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ushort?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, ushort? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UInt16);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>int</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(int value)
    {
        InternalAppendValueType(value, ArgumentType.Int32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>int?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(int? value)
    {
        InternalAppendValueType(value, ArgumentType.Int32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>int</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(int value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Int32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>int?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(int? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Int32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>int</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, int value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Int32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>int?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, int? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Int32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>uint</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(uint value)
    {
        InternalAppendValueType(value, ArgumentType.UInt32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>uint?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(uint? value)
    {
        InternalAppendValueType(value, ArgumentType.UInt32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>uint</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(uint value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UInt32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>uint?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(uint? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UInt32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>uint</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, uint value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UInt32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>uint?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, uint? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UInt32);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>long</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(long value)
    {
        InternalAppendValueType(value, ArgumentType.Int64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>long?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(long? value)
    {
        InternalAppendValueType(value, ArgumentType.Int64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>long</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(long value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Int64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>long?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(long? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Int64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>long</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, long value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Int64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>long?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, long? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Int64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ulong</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(ulong value)
    {
        InternalAppendValueType(value, ArgumentType.UInt64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ulong?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(ulong? value)
    {
        InternalAppendValueType(value, ArgumentType.UInt64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ulong</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(ulong value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UInt64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ulong?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(ulong? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UInt64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ulong</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, ulong value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UInt64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>ulong?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, ulong? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UInt64);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nint</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(nint value)
    {
        InternalAppendValueType(value, ArgumentType.IntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nint?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(nint? value)
    {
        InternalAppendValueType(value, ArgumentType.IntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nint</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(nint value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.IntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nint?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(nint? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.IntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nint</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, nint value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.IntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nint?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, nint? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.IntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nuint</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(nuint value)
    {
        InternalAppendValueType(value, ArgumentType.UIntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nuint?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(nuint? value)
    {
        InternalAppendValueType(value, ArgumentType.UIntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nuint</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(nuint value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UIntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nuint?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(nuint? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.UIntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nuint</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, nuint value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UIntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>nuint?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, nuint? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.UIntPtr);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>float</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(float value)
    {
        InternalAppendValueType(value, ArgumentType.Single);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>float?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(float? value)
    {
        InternalAppendValueType(value, ArgumentType.Single);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>float</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(float value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Single);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>float?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(float? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Single);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>float</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, float value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Single);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>float?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, float? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Single);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>double</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(double value)
    {
        InternalAppendValueType(value, ArgumentType.Double);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>double?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(double? value)
    {
        InternalAppendValueType(value, ArgumentType.Double);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>double</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(double value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Double);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>double?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(double? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Double);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>double</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, double value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Double);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>double?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, double? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Double);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>decimal</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(decimal value)
    {
        InternalAppendValueType(value, ArgumentType.Decimal);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>decimal?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(decimal? value)
    {
        InternalAppendValueType(value, ArgumentType.Decimal);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>decimal</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(decimal value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Decimal);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>decimal?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(decimal? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Decimal);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>decimal</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, decimal value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Decimal);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>decimal?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, decimal? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Decimal);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>Guid</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(Guid value)
    {
        InternalAppendValueType(value, ArgumentType.Guid);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>Guid?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(Guid? value)
    {
        InternalAppendValueType(value, ArgumentType.Guid);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>Guid</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(Guid value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Guid);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>Guid?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(Guid? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.Guid);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>Guid</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, Guid value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Guid);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>Guid?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, Guid? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.Guid);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTime</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(DateTime value)
    {
        InternalAppendValueType(value, ArgumentType.DateTime);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTime?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(DateTime? value)
    {
        InternalAppendValueType(value, ArgumentType.DateTime);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTime</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(DateTime value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.DateTime);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTime?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(DateTime? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.DateTime);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTime</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, DateTime value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.DateTime);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTime?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, DateTime? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.DateTime);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeSpan</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(TimeSpan value)
    {
        InternalAppendValueType(value, ArgumentType.TimeSpan);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeSpan?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(TimeSpan? value)
    {
        InternalAppendValueType(value, ArgumentType.TimeSpan);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeSpan</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(TimeSpan value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.TimeSpan);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeSpan?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(TimeSpan? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.TimeSpan);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeSpan</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, TimeSpan value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.TimeSpan);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeSpan?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, TimeSpan? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.TimeSpan);
        return this;
    }

#if NETCOREAPP

    /// <summary>
    /// Appends a value of type <c>DateOnly</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(DateOnly value)
    {
        InternalAppendValueType(value, ArgumentType.DateOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateOnly?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(DateOnly? value)
    {
        InternalAppendValueType(value, ArgumentType.DateOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateOnly</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(DateOnly value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.DateOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateOnly?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(DateOnly? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.DateOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateOnly</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, DateOnly value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.DateOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateOnly?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, DateOnly? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.DateOnly);
        return this;
    }

#endif

#if NETCOREAPP

    /// <summary>
    /// Appends a value of type <c>TimeOnly</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(TimeOnly value)
    {
        InternalAppendValueType(value, ArgumentType.TimeOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeOnly?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(TimeOnly? value)
    {
        InternalAppendValueType(value, ArgumentType.TimeOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeOnly</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(TimeOnly value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.TimeOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeOnly?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(TimeOnly? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.TimeOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeOnly</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, TimeOnly value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.TimeOnly);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>TimeOnly?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, TimeOnly? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.TimeOnly);
        return this;
    }

#endif

    /// <summary>
    /// Appends a value of type <c>DateTimeOffset</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(DateTimeOffset value)
    {
        InternalAppendValueType(value, ArgumentType.DateTimeOffset);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTimeOffset?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append(DateTimeOffset? value)
    {
        InternalAppendValueType(value, ArgumentType.DateTimeOffset);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTimeOffset</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(DateTimeOffset value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.DateTimeOffset);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTimeOffset?</c> to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    /// <param name="format">The format string.</param>
    public LogMessage Append(DateTimeOffset? value, string format)
    {
        InternalAppendValueType(value, format, ArgumentType.DateTimeOffset);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTimeOffset</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, DateTimeOffset value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.DateTimeOffset);
        return this;
    }

    /// <summary>
    /// Appends a value of type <c>DateTimeOffset?</c> to the message metadata.
    /// </summary>
    /// <param name="key">The key.</param>
    /// <param name="value">The value.</param>
    public LogMessage AppendKeyValue(string key, DateTimeOffset? value)
    {
        InternalAppendKeyValue(key, value, ArgumentType.DateTimeOffset);
        return this;
    }

    /// <summary>
    /// Appends an interpolated string to the message.
    /// </summary>
    /// <param name="value">The value to append.</param>
    public LogMessage Append([InterpolatedStringHandlerArgument("")] AppendInterpolatedStringHandler value)
        => this;

    partial struct AppendInterpolatedStringHandler
    {
        /// <summary>
        /// Appends a value of type <c>bool</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(bool value)
            => _message.InternalAppendValueType(value, ArgumentType.Boolean);

        /// <summary>
        /// Appends a value of type <c>bool?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(bool? value)
            => _message.InternalAppendValueType(value, ArgumentType.Boolean);

        /// <summary>
        /// Appends a value of type <c>byte</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(byte value)
            => _message.InternalAppendValueType(value, ArgumentType.Byte);

        /// <summary>
        /// Appends a value of type <c>byte?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(byte? value)
            => _message.InternalAppendValueType(value, ArgumentType.Byte);

        /// <summary>
        /// Appends a value of type <c>byte</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(byte value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Byte);

        /// <summary>
        /// Appends a value of type <c>byte?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(byte? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Byte);

        /// <summary>
        /// Appends a value of type <c>sbyte</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(sbyte value)
            => _message.InternalAppendValueType(value, ArgumentType.SByte);

        /// <summary>
        /// Appends a value of type <c>sbyte?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(sbyte? value)
            => _message.InternalAppendValueType(value, ArgumentType.SByte);

        /// <summary>
        /// Appends a value of type <c>sbyte</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(sbyte value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.SByte);

        /// <summary>
        /// Appends a value of type <c>sbyte?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(sbyte? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.SByte);

        /// <summary>
        /// Appends a value of type <c>char</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(char value)
            => _message.InternalAppendValueType(value, ArgumentType.Char);

        /// <summary>
        /// Appends a value of type <c>char?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(char? value)
            => _message.InternalAppendValueType(value, ArgumentType.Char);

        /// <summary>
        /// Appends a value of type <c>short</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(short value)
            => _message.InternalAppendValueType(value, ArgumentType.Int16);

        /// <summary>
        /// Appends a value of type <c>short?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(short? value)
            => _message.InternalAppendValueType(value, ArgumentType.Int16);

        /// <summary>
        /// Appends a value of type <c>short</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(short value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Int16);

        /// <summary>
        /// Appends a value of type <c>short?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(short? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Int16);

        /// <summary>
        /// Appends a value of type <c>ushort</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(ushort value)
            => _message.InternalAppendValueType(value, ArgumentType.UInt16);

        /// <summary>
        /// Appends a value of type <c>ushort?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(ushort? value)
            => _message.InternalAppendValueType(value, ArgumentType.UInt16);

        /// <summary>
        /// Appends a value of type <c>ushort</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(ushort value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UInt16);

        /// <summary>
        /// Appends a value of type <c>ushort?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(ushort? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UInt16);

        /// <summary>
        /// Appends a value of type <c>int</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(int value)
            => _message.InternalAppendValueType(value, ArgumentType.Int32);

        /// <summary>
        /// Appends a value of type <c>int?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(int? value)
            => _message.InternalAppendValueType(value, ArgumentType.Int32);

        /// <summary>
        /// Appends a value of type <c>int</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(int value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Int32);

        /// <summary>
        /// Appends a value of type <c>int?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(int? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Int32);

        /// <summary>
        /// Appends a value of type <c>uint</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(uint value)
            => _message.InternalAppendValueType(value, ArgumentType.UInt32);

        /// <summary>
        /// Appends a value of type <c>uint?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(uint? value)
            => _message.InternalAppendValueType(value, ArgumentType.UInt32);

        /// <summary>
        /// Appends a value of type <c>uint</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(uint value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UInt32);

        /// <summary>
        /// Appends a value of type <c>uint?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(uint? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UInt32);

        /// <summary>
        /// Appends a value of type <c>long</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(long value)
            => _message.InternalAppendValueType(value, ArgumentType.Int64);

        /// <summary>
        /// Appends a value of type <c>long?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(long? value)
            => _message.InternalAppendValueType(value, ArgumentType.Int64);

        /// <summary>
        /// Appends a value of type <c>long</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(long value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Int64);

        /// <summary>
        /// Appends a value of type <c>long?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(long? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Int64);

        /// <summary>
        /// Appends a value of type <c>ulong</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(ulong value)
            => _message.InternalAppendValueType(value, ArgumentType.UInt64);

        /// <summary>
        /// Appends a value of type <c>ulong?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(ulong? value)
            => _message.InternalAppendValueType(value, ArgumentType.UInt64);

        /// <summary>
        /// Appends a value of type <c>ulong</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(ulong value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UInt64);

        /// <summary>
        /// Appends a value of type <c>ulong?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(ulong? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UInt64);

        /// <summary>
        /// Appends a value of type <c>nint</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(nint value)
            => _message.InternalAppendValueType(value, ArgumentType.IntPtr);

        /// <summary>
        /// Appends a value of type <c>nint?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(nint? value)
            => _message.InternalAppendValueType(value, ArgumentType.IntPtr);

        /// <summary>
        /// Appends a value of type <c>nint</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(nint value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.IntPtr);

        /// <summary>
        /// Appends a value of type <c>nint?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(nint? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.IntPtr);

        /// <summary>
        /// Appends a value of type <c>nuint</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(nuint value)
            => _message.InternalAppendValueType(value, ArgumentType.UIntPtr);

        /// <summary>
        /// Appends a value of type <c>nuint?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(nuint? value)
            => _message.InternalAppendValueType(value, ArgumentType.UIntPtr);

        /// <summary>
        /// Appends a value of type <c>nuint</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(nuint value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UIntPtr);

        /// <summary>
        /// Appends a value of type <c>nuint?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(nuint? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.UIntPtr);

        /// <summary>
        /// Appends a value of type <c>float</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(float value)
            => _message.InternalAppendValueType(value, ArgumentType.Single);

        /// <summary>
        /// Appends a value of type <c>float?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(float? value)
            => _message.InternalAppendValueType(value, ArgumentType.Single);

        /// <summary>
        /// Appends a value of type <c>float</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(float value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Single);

        /// <summary>
        /// Appends a value of type <c>float?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(float? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Single);

        /// <summary>
        /// Appends a value of type <c>double</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(double value)
            => _message.InternalAppendValueType(value, ArgumentType.Double);

        /// <summary>
        /// Appends a value of type <c>double?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(double? value)
            => _message.InternalAppendValueType(value, ArgumentType.Double);

        /// <summary>
        /// Appends a value of type <c>double</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(double value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Double);

        /// <summary>
        /// Appends a value of type <c>double?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(double? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Double);

        /// <summary>
        /// Appends a value of type <c>decimal</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(decimal value)
            => _message.InternalAppendValueType(value, ArgumentType.Decimal);

        /// <summary>
        /// Appends a value of type <c>decimal?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(decimal? value)
            => _message.InternalAppendValueType(value, ArgumentType.Decimal);

        /// <summary>
        /// Appends a value of type <c>decimal</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(decimal value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Decimal);

        /// <summary>
        /// Appends a value of type <c>decimal?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(decimal? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Decimal);

        /// <summary>
        /// Appends a value of type <c>Guid</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(Guid value)
            => _message.InternalAppendValueType(value, ArgumentType.Guid);

        /// <summary>
        /// Appends a value of type <c>Guid?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(Guid? value)
            => _message.InternalAppendValueType(value, ArgumentType.Guid);

        /// <summary>
        /// Appends a value of type <c>Guid</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(Guid value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Guid);

        /// <summary>
        /// Appends a value of type <c>Guid?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(Guid? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.Guid);

        /// <summary>
        /// Appends a value of type <c>DateTime</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(DateTime value)
            => _message.InternalAppendValueType(value, ArgumentType.DateTime);

        /// <summary>
        /// Appends a value of type <c>DateTime?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(DateTime? value)
            => _message.InternalAppendValueType(value, ArgumentType.DateTime);

        /// <summary>
        /// Appends a value of type <c>DateTime</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(DateTime value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.DateTime);

        /// <summary>
        /// Appends a value of type <c>DateTime?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(DateTime? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.DateTime);

        /// <summary>
        /// Appends a value of type <c>TimeSpan</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(TimeSpan value)
            => _message.InternalAppendValueType(value, ArgumentType.TimeSpan);

        /// <summary>
        /// Appends a value of type <c>TimeSpan?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(TimeSpan? value)
            => _message.InternalAppendValueType(value, ArgumentType.TimeSpan);

        /// <summary>
        /// Appends a value of type <c>TimeSpan</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(TimeSpan value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.TimeSpan);

        /// <summary>
        /// Appends a value of type <c>TimeSpan?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(TimeSpan? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.TimeSpan);

#if NETCOREAPP

        /// <summary>
        /// Appends a value of type <c>DateOnly</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(DateOnly value)
            => _message.InternalAppendValueType(value, ArgumentType.DateOnly);

        /// <summary>
        /// Appends a value of type <c>DateOnly?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(DateOnly? value)
            => _message.InternalAppendValueType(value, ArgumentType.DateOnly);

        /// <summary>
        /// Appends a value of type <c>DateOnly</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(DateOnly value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.DateOnly);

        /// <summary>
        /// Appends a value of type <c>DateOnly?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(DateOnly? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.DateOnly);

#endif

#if NETCOREAPP

        /// <summary>
        /// Appends a value of type <c>TimeOnly</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(TimeOnly value)
            => _message.InternalAppendValueType(value, ArgumentType.TimeOnly);

        /// <summary>
        /// Appends a value of type <c>TimeOnly?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(TimeOnly? value)
            => _message.InternalAppendValueType(value, ArgumentType.TimeOnly);

        /// <summary>
        /// Appends a value of type <c>TimeOnly</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(TimeOnly value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.TimeOnly);

        /// <summary>
        /// Appends a value of type <c>TimeOnly?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(TimeOnly? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.TimeOnly);

#endif

        /// <summary>
        /// Appends a value of type <c>DateTimeOffset</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(DateTimeOffset value)
            => _message.InternalAppendValueType(value, ArgumentType.DateTimeOffset);

        /// <summary>
        /// Appends a value of type <c>DateTimeOffset?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        public void AppendFormatted(DateTimeOffset? value)
            => _message.InternalAppendValueType(value, ArgumentType.DateTimeOffset);

        /// <summary>
        /// Appends a value of type <c>DateTimeOffset</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(DateTimeOffset value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.DateTimeOffset);

        /// <summary>
        /// Appends a value of type <c>DateTimeOffset?</c> to the handler.
        /// </summary>
        /// <param name="value">The value to append.</param>
        /// <param name="format">The format string.</param>
        public void AppendFormatted(DateTimeOffset? value, string format)
            => _message.InternalAppendValueType(value, format, ArgumentType.DateTimeOffset);

    }
}
