<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroLog\ZeroLog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.NUnit" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="PublicApiGenerator" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../ZeroLog.Tests/Support/AssertExtensions.cs" Link="Support/AssertExtensions.cs" />
  </ItemGroup>

</Project>
