<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <NoWarn>$(NoWarn);CS8002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroLog\ZeroLog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Verify.NUnit" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="PublicApiGenerator" />
    <PackageReference Include="ObjectLayoutInspector" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LogTests.Messages.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LogTests.Messages.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LogTests.Messages.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>LogTests.Messages.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
