//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("ZeroLog")]
[assembly: AssemblyDescription("A zero-allocation .NET logging library - https://github.com/Abc-Arbitrage/ZeroLog")]
[assembly: AssemblyCompany("ABC arbitrage")]
[assembly: AssemblyProduct("ZeroLog")]
[assembly: AssemblyCopyright("Copyright © ABC arbitrage 2017")]

[assembly: InternalsVisibleTo("ZeroLog.Tests")]

