<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>roslyn4.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <NoWarn>$(NoWarn);RS2008</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworkIdentifier>.NETStandard</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="[4.0.1]" PrivateAssets="all" Condition="'$(TargetFramework)' == 'roslyn4.0'" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../ZeroLog/Properties/AssemblyData.cs" Link="Properties/AssemblyData.cs" />
    <Compile Include="../ZeroLog.Impl.Base/LogLevel.cs" Link="Library/%(Filename)%(Extension)" />
    <Compile Include="../ZeroLog.Impl.Full/Formatting/AnsiColorCodes.cs" Link="Library/%(Filename)%(Extension)" />
    <Compile Include="../ZeroLog.Impl.Full/Formatting/PatternWriter.cs" Link="Library/%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
