//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using JetBrains.Annotations;

namespace ZeroLog
{
    partial interface ILog
    {
        bool IsDebugEnabled { get; }
        bool IsInfoEnabled { get; }
        bool IsWarnEnabled { get; }
        bool IsErrorEnabled { get; }
        bool IsFatalEnabled { get; }

        ILogEvent Debug();
        void Debug(string? message);
        void Debug(string? message, Exception? ex);

        ILogEvent Info();
        void Info(string? message);
        void Info(string? message, Exception? ex);

        ILogEvent Warn();
        void Warn(string? message);
        void Warn(string? message, Exception? ex);

        ILogEvent Error();
        void Error(string? message);
        void Error(string? message, Exception? ex);

        ILogEvent Fatal();
        void Fatal(string? message);
        void Fatal(string? message, Exception? ex);

    }

    partial class Log
    {
        public bool IsDebugEnabled => Level.Debug >= _logLevel;

        public ILogEvent Debug()
        {
            return IsDebugEnabled
                ? GetLogEventFor(Level.Debug)
                : NoopLogEvent.Instance;
        }

        public void Debug(string? message)
        {
            if (!IsDebugEnabled)
                return;

            GetLogEventFor(Level.Debug).Append(message).Log();
        }

        public void Debug(string? message, Exception? ex)
        {
            if (!IsDebugEnabled)
                return;

            var logEvent = GetLogEventFor(Level.Debug);
            logEvent.Append(message);
            logEvent.Append(ex?.ToString());
            logEvent.Log();
        }

        public bool IsInfoEnabled => Level.Info >= _logLevel;

        public ILogEvent Info()
        {
            return IsInfoEnabled
                ? GetLogEventFor(Level.Info)
                : NoopLogEvent.Instance;
        }

        public void Info(string? message)
        {
            if (!IsInfoEnabled)
                return;

            GetLogEventFor(Level.Info).Append(message).Log();
        }

        public void Info(string? message, Exception? ex)
        {
            if (!IsInfoEnabled)
                return;

            var logEvent = GetLogEventFor(Level.Info);
            logEvent.Append(message);
            logEvent.Append(ex?.ToString());
            logEvent.Log();
        }

        public bool IsWarnEnabled => Level.Warn >= _logLevel;

        public ILogEvent Warn()
        {
            return IsWarnEnabled
                ? GetLogEventFor(Level.Warn)
                : NoopLogEvent.Instance;
        }

        public void Warn(string? message)
        {
            if (!IsWarnEnabled)
                return;

            GetLogEventFor(Level.Warn).Append(message).Log();
        }

        public void Warn(string? message, Exception? ex)
        {
            if (!IsWarnEnabled)
                return;

            var logEvent = GetLogEventFor(Level.Warn);
            logEvent.Append(message);
            logEvent.Append(ex?.ToString());
            logEvent.Log();
        }

        public bool IsErrorEnabled => Level.Error >= _logLevel;

        public ILogEvent Error()
        {
            return IsErrorEnabled
                ? GetLogEventFor(Level.Error)
                : NoopLogEvent.Instance;
        }

        public void Error(string? message)
        {
            if (!IsErrorEnabled)
                return;

            GetLogEventFor(Level.Error).Append(message).Log();
        }

        public void Error(string? message, Exception? ex)
        {
            if (!IsErrorEnabled)
                return;

            var logEvent = GetLogEventFor(Level.Error);
            logEvent.Append(message);
            logEvent.Append(ex?.ToString());
            logEvent.Log();
        }

        public bool IsFatalEnabled => Level.Fatal >= _logLevel;

        public ILogEvent Fatal()
        {
            return IsFatalEnabled
                ? GetLogEventFor(Level.Fatal)
                : NoopLogEvent.Instance;
        }

        public void Fatal(string? message)
        {
            if (!IsFatalEnabled)
                return;

            GetLogEventFor(Level.Fatal).Append(message).Log();
        }

        public void Fatal(string? message, Exception? ex)
        {
            if (!IsFatalEnabled)
                return;

            var logEvent = GetLogEventFor(Level.Fatal);
            logEvent.Append(message);
            logEvent.Append(ex?.ToString());
            logEvent.Log();
        }

    }

    partial class NoopLogManager
    {
        partial class NoopLog
        {
            public bool IsDebugEnabled => false;

            public ILogEvent Debug()
                => NoopLogEvent.Instance;

            public void Debug(string? message)
            {
            }

            public void Debug(string? message, Exception? ex)
            {
            }
            public bool IsInfoEnabled => false;

            public ILogEvent Info()
                => NoopLogEvent.Instance;

            public void Info(string? message)
            {
            }

            public void Info(string? message, Exception? ex)
            {
            }
            public bool IsWarnEnabled => false;

            public ILogEvent Warn()
                => NoopLogEvent.Instance;

            public void Warn(string? message)
            {
            }

            public void Warn(string? message, Exception? ex)
            {
            }
            public bool IsErrorEnabled => false;

            public ILogEvent Error()
                => NoopLogEvent.Instance;

            public void Error(string? message)
            {
            }

            public void Error(string? message, Exception? ex)
            {
            }
            public bool IsFatalEnabled => false;

            public ILogEvent Fatal()
                => NoopLogEvent.Instance;

            public void Fatal(string? message)
            {
            }

            public void Fatal(string? message, Exception? ex)
            {
            }
        }
    }
}
